# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VContact' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.8'
  # Pods for VContact
pod 'RealmSwift'
pod 'Kingfisher', '~> 7.2'
pod 'FirebaseCore'
pod 'FirebaseDatabase'
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
end
